apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: meetup-bot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: app-block-storage
